#!/bin/bash

set -e
set -o pipefail

REFORM_URI=$1
TABLE_URI=$2

SCRIPT_DIRECTORY=$(dirname "${BASH_SOURCE}")

if [[ -z $AWS_ACCESS_KEY_ID || -z $AWS_SECRET_ACCESS_KEY || -z $S3_BUCKET || -z $SNOWSQL_PWD || -z $ACCOUNT || -z $SNOWFLAKE_USER || -z $WAREHOUSE || -z $DB || -z $TABLE_URI ]]; then
  echo 'Invalid usage'
  echo ''
  echo 'The table uri must be provided as an argument and the following variables must be defined:'
  echo ''
  echo 'AWS_ACCESS_KEY_ID'
  echo 'AWS_SECRET_ACCESS_KEY'
  echo 'S3_BUCKET'
  echo 'SNOWSQL_PWD'
  echo 'ACCOUNT'
  echo 'SNOWFLAKE_USER'
  echo 'WAREHOUSE'
  echo 'DB'
  exit 1
fi

TABLE_ID=${TABLE_URI##*/}
TABLE_INFO=$(curl $TABLE_URI)
TABLE_NAME=$(echo "${TABLE_INFO}" | jq -r .name | perl -pe 'chomp if eof' | perl -pe 's/[^A-Za-z0-9]/_/g' | tr '[:upper:]' '[:lower:]')
DESTINATION_URI="${S3_BUCKET}/${TABLE_NAME}"
TOKEN=$(curl --silent -X POST ${TABLE_URI}/access-token | jq -r '.secret')

curl --silent ${REFORM_URI}/api/result/${TOKEN}.csv | aws s3 cp - $DESTINATION_URI
TABLE_INFO=$TABLE_INFO $SCRIPT_DIRECTORY/copytable-snowflake > $SCRIPT_DIRECTORY/copytable-snowflake-output.sql;
cat $SCRIPT_DIRECTORY/copytable-snowflake-output.sql;
snowsql -a $ACCOUNT -u $SNOWFLAKE_USER -f $SCRIPT_DIRECTORY/copytable-snowflake-output.sql
