#!/usr/bin/env bash
SCRIPT_DIRECTORY="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_DEFAULT_REGION=us-east-1

export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_DEFAULT_REGION

S3_BUCKET="s3://example" ACCOUNT="example" SNOWFLAKE_USER="example" SNOWSQL_PWD="example" WAREHOUSE="EXAMPLE" DB="EXAMPLE" SCHEMA="EXAMPLE" "$SCRIPT_DIRECTORY/alltables-snowflake" https://localhost
