#!/bin/bash

set -e
set -o pipefail

PUBLIC_KEY=$1

sudo yum -y install jq

sudo yum -y install postgresql

curl -o copytable https://raw.githubusercontent.com/slamdata/reform-push/master/redshift/copytable

chmod +x copytable

curl -o transfer https://raw.githubusercontent.com/slamdata/reform-push/master/redshift/transfer

chmod +x transfer

curl -o manifest https://raw.githubusercontent.com/slamdata/reform-push/master/redshift/manifest

chmod +x manifest

curl -o alltables https://raw.githubusercontent.com/slamdata/reform-push/master/redshift/alltables

chmod +x alltables

cat <<< "${PUBLIC_KEY}" >> ~/.ssh/authorized_keys
